services:
  db:
    image: postgres:15-alpine
    container_name: adchannel-db
    restart: unless-stopped
    ports:
      - "1337:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adchannel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d adchannel" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #  web:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile.Web
  #    container_name: adchannel-web
  #    restart: unless-stopped
  #    ports:
  #      - "5000:8080"
  #    environment:
  #      - ASPNETCORE_ENVIRONMENT=Development
  #      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=adchannel;Username=postgres;Password=postgres;
  #    depends_on:
  #      db:
  #        condition: service_healthy
  #      ollama:
  #        condition: service_started

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    command: serve
    restart: unless-stopped

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.Daemon
    container_name: adchannel-daemon
    depends_on:
      - db
      - ollama
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=adchannel;Username=postgres;Password=postgres;
    restart: unless-stopped

volumes:
  postgres_data:
  ollama:

# Опционально: запуск миграций при старте
# command: >
#   sh -c "dotnet ef database update --project ../infrastructure/Persistence && dotnet watch run"
